[tool.mypy]
disable_error_code = ["arg-type", "attr-defined", "index", "name-defined"]
strict = true
warn_return_any = true
warn_unused_configs = true

[[tool.mypy.overrides]]
module = "numba.*"
follow_imports = "skip"

[[tool.mypy.overrides]]
module = "infix.*"
warn_return_any = false

[[tool.mypy.overrides]]
module = ["untyped_package.*"]
follow_untyped_imports = true
