[tool.mypy]
strict = true
warn_return_any = true
warn_unused_configs = true

[[tool.mypy.overrides]]
module = "numba.*"
follow_imports = "skip"

[[tool.mypy.overrides]]
module = "infix.*"
warn_return_any = false
